### ISSUE TITLE
pygalmesh-volume-from-surface triggers DistributionNotFound exception

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#30]
I just noticed the /usr/bin/pygalmesh-volume-from-surface utility

It doesn't work in a Debian installation (0.3.3-2), generating a pipdate DistributionNotFound exception:

    $ pygalmesh-volume-from-surface 
    Traceback (most recent call last):
      File "/usr/bin/pygalmesh-volume-from-surface", line 6, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pipdate' distribution was not found and is required by pygalmesh

Does some configuration setting need to be set?

**Comment by nschloe** [comment]
There were still some pipdate leftovers. Hopefully fixed now in v0.3.5.
