### ISSUE TITLE
 import pygalmesh Error

### ISSUE THREAD

**Issue by lgribeiro** [nschloe/pygalmesh#37]
Hi,
I am having some trouble when importing pygalmesh. I work on Ubuntu 16.04 lts . I successfully installed CGAL 4.14 (https://doc.cgal.org/latest/Manual/installation.html) and Eigen (https://bitbucket.org/eigen/eigen/src/default/INSTALL)

`pip3 install -U pygalmesh`
```
Collecting pygalmesh
  Using cached https://files.pythonhosted.org/packages/4e/13/aaa7cecd775040d95eaae6e32cb32b7b8dc6dbc08adc950c0bb5fba7bdf9/pygalmesh-0.3.6.tar.gz
Requirement already satisfied, skipping upgrade: meshio in /home/ribeiro/.virtualenvs/flow/lib/python3.6/site-packages (from pygalmesh) (2.3.10)
Requirement already satisfied, skipping upgrade: numpy in /home/ribeiro/.virtualenvs/flow/lib/python3.6/site-packages (from pygalmesh) (1.15.4)
Requirement already satisfied, skipping upgrade: pybind11>=2.2 in /home/ribeiro/.virtualenvs/flow/lib/python3.6/site-packages (from pygalmesh) (2.3.0)
Building wheels for collected packages: pygalmesh
  Building wheel for pygalmesh (setup.py) ... done
  Stored in directory: /home/ribeiro/.cache/pip/wheels/1c/8a/67/e42306208f268f91849bc411cb414e9b70e204c747fa36a76c
Successfully built pygalmesh
Installing collected packages: pygalmesh
Successfully installed pygalmesh-0.3.6
```
but when I import pygalmesh I get this error :
```
(env) user@user:~/CGAL-4.14$ python 
Python 3.6.4 (default, Dec 12 2018, 16:31:54) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygalmesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ribeiro/.virtualenvs/flow/lib/python3.6/site-packages/pygalmesh/__init__.py", line 4, in <module>
    from _pygalmesh import (
ImportError: /home/ribeiro/.virtualenvs/flow/lib/python3.6/site-packages/_pygalmesh.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4CGAL7Image_312private_readEP11point_imageNS0_3OwnE
>>> 
```

Do you have any idea about this error ?
Thank you.

**Comment by lgribeiro** [comment]
I've got the solution
I downloaded the old version https://github.com/nschloe/pygalmesh/releases/tag/v0.3.3 and I installed with the comand:
`python setup.py install `
[]s
