### ISSUE TITLE
ImportError: cannot import name '__copyright__' from 'pygalmesh.__about__'

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/pygalmesh#73]
`_cli/helpers.py` strives to import `__copyright__` from `__about__`, but there is no such symbol.

Detected by unit tests:

    ERROR: pygalmesh._cli (unittest.loader._FailedTest)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: pygalmesh._cli
    Traceback (most recent call last):
      File "/usr/lib/python3.8/unittest/loader.py", line 470, in _find_test_path
        package = self._get_module_from_name(name)
      File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
        __import__(name)
      File "/home/build/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build/pygalmesh/_cli/__init__.py", line 1, in <module>
        from ._inr import inr
      File "/home/build/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build/pygalmesh/_cli/_inr.py", line 6, in <module>
        from .helpers import _get_version_text
      File "/home/build/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build/pygalmesh/_cli/helpers.py", line 5, in <module>
        from ..__about__ import __copyright__, __version__
    ImportError: cannot import name '__copyright__' from 'pygalmesh.__about__' (/home/build/pygalmesh/.pybuild/cpython3_3.8_pygalmesh/build/pygalmesh/__about__.py)

**Comment by nschloe** [comment]
Fixed in 0.6.2.
