### ISSUE TITLE
How to generate volume from a set of vertices and triangular faces?

### ISSUE THREAD

**Issue by montallban** [nschloe/pygalmesh#93]
Hi, I looked through the pygalmesh tutorial but haven't been able to find what I'm looking for. 

Basically, I have a series of vertices:
```
verts = [[0.1, 1.,  1. ]  [1.,  1.,  0.1]  [1.,  0.1, 1. ]  [1.,  1.,  1.9]  [1.,  1.9, 1. ]
 [1.9, 1.,  1. ] ]
```
And triangular faces, which define the vertices composing each faces:
```
faces = [[ 2,  1,  0]  [ 0,  3,  2]  [ 1,  4,  0]  [ 0,  4,  3]  [ 5,  1,  2]  [ 3,  5,  2]
 [ 5,  4,  1]  [ 4,  5,  3]]
```
How do I use pygalmesh to find the scalar volume for this object? It isn't clear from the [examples](https://github.com/nschloe/pygalmesh) how I can do this.  Perhaps there is a tutorial I am missing?

[Here](https://stackoverflow.com/questions/61569196/given-a-set-of-triangle-vertices-and-faces-separate-objects-and-form-separate-m) is a fuller explanation of my project, if interested. Thanks in advance!

**Comment by nschloe** [comment]
By volume you mean the enclosed volume (3D) or the surface?

**Comment by montallban** [comment]
@nschloe I mean the enclosed volume (3D)

**Comment by nschloe** [comment]
I'd simply create the tetrahedral volume mesh with pygalmesh and then sum up the volumes of the tetrahedra, perhaps with https://github.com/nschloe/meshplex.

**Comment by montallban** [comment]
Awesome, this seems to be exactly what I am looking for. Excuse me for my ignorance, but could you detail how to "create the tetrahedral volume mesh". I tried the following but I am not sure it is right:
```
mesh = pygalmesh.generate_mesh(verts[faces])
``` 
With ```faces``` and ```verts``` as above. I am returned with the error:
```
  File "C:\Users\User\Anaconda3\lib\site-packages\pygalmesh\main.py", line 53, in generate_mesh
    verbose=verbose,
TypeError: _generate_mesh(): incompatible function arguments. The following argument types are supported:
    1. (domain: _pygalmesh.DomainBase, outfile: str, feature_edges: List[List[List[float[3]]]] = [], bounding_sphere_radius: float = 0.0, lloyd: bool = False, odt: bool = False, perturb: bool = True, exude: bool = True, edge_size: float = 0.0, facet_angle: float = 0.0, facet_size: float = 0.0, facet_distance: float = 0.0, cell_radius_edge_ratio: float = 0.0, cell_size: float = 0.0, verbose: bool = True) -> None

Invoked with: array([[[0. , 1. , 1.9],
        [1. , 0. , 1.9],
        [0. , 0. , 1.9]],

       [[0. , 1. , 1.9],
        [1. , 1. , 1.9],
        [1. , 0. , 1.9]],

       [[0. , 1.9, 0. ],
        [1. , 1.9, 1. ],
        [0. , 1.9, 1. ]],

       [[1. , 1.9, 0. ],
        [1. , 1.9, 1. ],
        [0. , 1.9, 0. ]],

       [[0. , 1. , 1.9],
        [0. , 1.9, 1. ],
        [1. , 1. , 1.9]],

       [[1. , 1. , 1.9],
        [0. , 1.9, 1. ],
        [1. , 1.9, 1. ]],

       [[1.9, 1. , 1. ],
        [1.9, 0. , 0. ],
        [1.9, 0. , 1. ]],

       [[1.9, 1. , 0. ],
        [1.9, 0. , 0. ],
        [1.9, 1. , 1. ]],

       [[1. , 1. , 1.9],
        [1.9, 1. , 1. ],
        [1. , 0. , 1.9]],

       [[1. , 0. , 1.9],
        [1.9, 1. , 1. ],
        [1.9, 0. , 1. ]],

       [[1. , 1.9, 0. ],
        [1.9, 1. , 0. ],
        [1. , 1.9, 1. ]],

       [[1. , 1.9, 1. ],
        [1.9, 1. , 0. ],
        [1.9, 1. , 1. ]],

       [[1. , 1.9, 1. ],
        [1.9, 1. , 1. ],
        [1. , 1. , 1.9]]], dtype=float32), 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpjm5w3m1i.mesh'; kwargs: feature_edges=[], bounding_sphere_radius=0.0, lloyd=False, odt=False, perturb=True, exude=True, edge_size=0.0, facet_angle=0.0, facet_size=0.0, facet_distance=0.0, cell_radius_edge_ratio=0.0, cell_size=0.0, verbose=True
```

**Comment by nschloe** [comment]
https://github.com/nschloe/pygalmesh#volume-meshes-from-surface-meshes

**Comment by montallban** [comment]
Can you explain to me how to get my surface mesh in the correct form? This is how I am doing it:
```
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

mesh = Poly3DCollection(verts[faces])
mesh = pygalmesh.generate_volume_mesh_from_surface_mesh(mesh)
```
returns
```
Traceback (most recent call last):
  File "c:\Users\User\weather\MS\MS_cubes.py", line 137, in <module>
  File "C:\Users\User\Anaconda3\lib\site-packages\pygalmesh\main.py", line 189, in generate_volume_mesh_from_surface_mesh
    mesh = meshio.read(filename)
  File "C:\Users\User\Anaconda3\lib\site-packages\meshio\_helpers.py", line 55, in read
    path = pathlib.Path(filename)
  File "C:\Users\User\Anaconda3\lib\pathlib.py", line 1003, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\User\Anaconda3\lib\pathlib.py", line 658, in _from_parts
  File "C:\Users\User\Anaconda3\lib\pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not Poly3DCollection
```
I am new to this, I'd really appreciate baby steps or a relevant tutorial. I have a numpy array which I convert into a mesh using Poly3DCollection. It is not in the '.vtu' format.

**Comment by montallban** [comment]
I can just make a stackoverflow post if you're not willing to help someone use your module?
